/*
 * us-device-api
 *
 * System API for U/S device components
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"philips/us/sample-api-docker/impl"

	"github.com/gin-gonic/gin"
)

// DeleteHw -
func DeleteHw(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetHwComponent -
func GetHwComponent(c *gin.Context) {
	c.JSON(http.StatusOK, impl.GetHwComponent(c))
}

// Register -
func Register(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
