/*
 * us-device-api
 *
 * System API for U/S device components
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteHw -
func DeleteHw(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetHwComponent -
func GetHwComponent(c *gin.Context) {
	hwInfo := US_GetHwComponent()
	jsonText, err := json.Marshal(hwInfo)
	if err == nil {
		var m map[string]interface{}
		json.Unmarshal(jsonText, &m)
		c.JSON(http.StatusOK, m)
		return
	}
	c.JSON(http.StatusInternalServerError, "Could not deserialize")
}

// Register -
func Register(c *gin.Context) {
	hwRegInfo := US_Register()
	jsonText, err := json.Marshal(hwRegInfo)
	if err == nil {
		var m map[string]interface{}
		json.Unmarshal(jsonText, &m)
		c.JSON(http.StatusOK, m)
		return
	}
	c.JSON(http.StatusInternalServerError, "Could not deserialize")
}
