# This is a basic workflow to help you get started with Actions

name: api-CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: go version

      # Runs a single command using the runners shell
      - name: Go environment
        run: go env

      # Runs a set of commands using the runners shell
      - name: Auto-generate code using openapi-generator
        run: |
          docker pull openapitools/openapi-generator-cli
          docker run openapitools/openapi-generator-cli list          
          mkdir -p ./src
          export GO_POST_PROCESS_FILE="/usr/local/bin/gofmt -w"
          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate -i /local/api.yaml -g go-gin-server -o /local/src
          sudo cp ./main.go ./src/
      - name: Install go dependencies
        run: |
          cd ./src
          echo "----------------------"
          go version
          pwd
          ls -ls
          echo "----------------------"
          go mod init philips/us/sample-api-docker
          go mod tidy
          go get -d -v ./...
      # Every step starts in the same base directory
      - name: Build the code
        run: |
          cd ./src
          export CGO_ENABLED=0
          go build -a -installsuffix cgo -o sample-api-docker .
          ls -ls
          echo test, and deploy your project.
      - name: Build the docker image
        run: |
          docker build -t philips/us/sample-api-docker .
          docker images
      - name: Test the docker image
        run: |
          docker run -d -p 8080:8080 --name philips-us-api philips/us/sample-api-docker
          sleep 3
          docker ps
          curl
          echo "Done Testing"
